# Generated by Django 5.1.6 on 2025-02-14 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id_post', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Acessos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abertura', models.DateTimeField(db_index=True)),
                ('leitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos', to=settings.AUTH_USER_MODEL)),
                ('id_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos', to='webhook.posts')),
            ],
        ),
        migrations.CreateModel(
            name='UTM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utm_source', models.CharField(db_index=True, max_length=50)),
                ('utm_medium', models.CharField(db_index=True, max_length=50)),
                ('utm_campaign', models.CharField(db_index=True, max_length=50)),
                ('utm_channel', models.CharField(db_index=True, max_length=50)),
                ('utm_variaveis', models.JSONField()),
                ('acesso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utms', to='webhook.acessos')),
            ],
        ),
        migrations.AddIndex(
            model_name='acessos',
            index=models.Index(fields=['leitor', 'abertura'], name='webhook_ace_leitor__b94a46_idx'),
        ),
        migrations.AddIndex(
            model_name='acessos',
            index=models.Index(fields=['id_post', 'abertura'], name='webhook_ace_id_post_6c11b3_idx'),
        ),
    ]
