# Generated by Django 5.1.6 on 2025-02-14 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utm',
            old_name='utm_campaign',
            new_name='campaign',
        ),
        migrations.RenameField(
            model_name='utm',
            old_name='utm_channel',
            new_name='channel',
        ),
        migrations.RenameField(
            model_name='utm',
            old_name='utm_medium',
            new_name='medium',
        ),
        migrations.RenameField(
            model_name='utm',
            old_name='utm_source',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='utm',
            old_name='utm_variaveis',
            new_name='variaveis',
        ),
    ]
