# Generated by Django 5.1.6 on 2025-02-14 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0002_rename_utm_campaign_utm_campaign_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utm',
            name='variaveis',
        ),
    ]
