# Generated by Django 5.1.6 on 2025-02-14 23:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0003_remove_utm_variaveis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='acessos',
            name='webhook_ace_leitor__b94a46_idx',
        ),
        migrations.RemoveIndex(
            model_name='acessos',
            name='webhook_ace_id_post_6c11b3_idx',
        ),
        migrations.RemoveField(
            model_name='acessos',
            name='abertura',
        ),
        migrations.AddField(
            model_name='acessos',
            name='abertura_dia',
            field=models.DateField(db_index=True, default='2025-02-14'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acessos',
            name='abertura_hora',
            field=models.TimeField(db_index=True, default='20:01:05'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='utm',
            name='campaign',
            field=models.CharField(db_index=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='utm',
            name='channel',
            field=models.CharField(db_index=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='utm',
            name='medium',
            field=models.CharField(db_index=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='utm',
            name='source',
            field=models.CharField(db_index=True, default=None, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='acessos',
            index=models.Index(fields=['leitor', 'abertura_dia'], name='webhook_ace_leitor__ab8336_idx'),
        ),
        migrations.AddIndex(
            model_name='acessos',
            index=models.Index(fields=['leitor', 'abertura_hora'], name='webhook_ace_leitor__029c37_idx'),
        ),
        migrations.AddIndex(
            model_name='acessos',
            index=models.Index(fields=['id_post', 'abertura_dia'], name='webhook_ace_id_post_429e7f_idx'),
        ),
        migrations.AddIndex(
            model_name='acessos',
            index=models.Index(fields=['id_post', 'abertura_hora'], name='webhook_ace_id_post_9bf34f_idx'),
        ),
    ]
