# Generated by Django 5.1.6 on 2025-02-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0004_remove_acessos_webhook_ace_leitor__b94a46_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acessos',
            name='abertura_dia_semana',
            field=models.IntegerField(db_index=True, default=5),
            preserve_default=False,
        ),
    ]
