# Generated by Django 5.1.6 on 2025-02-17 00:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0005_acessos_abertura_dia_semana'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='acessos',
            name='webhook_ace_id_post_429e7f_idx',
        ),
        migrations.RemoveIndex(
            model_name='acessos',
            name='webhook_ace_id_post_9bf34f_idx',
        ),
        migrations.RenameField(
            model_name='acessos',
            old_name='id_post',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='id_post',
            new_name='id',
        ),
        migrations.AddIndex(
            model_name='acessos',
            index=models.Index(fields=['post', 'abertura_dia'], name='webhook_ace_post_id_19f194_idx'),
        ),
        migrations.AddIndex(
            model_name='acessos',
            index=models.Index(fields=['post', 'abertura_hora'], name='webhook_ace_post_id_71f1ca_idx'),
        ),
    ]
