# Generated by Django 5.1.6 on 2025-02-17 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0006_remove_acessos_webhook_ace_id_post_429e7f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='resource_id',
            field=models.CharField(db_index=True, default='2025-02-17'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posts',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
