# Generated by Django 5.1.6 on 2025-02-18 02:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0007_posts_resource_id_alter_posts_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='acessos',
            name='webhook_ace_leitor__ab8336_idx',
        ),
        migrations.RemoveIndex(
            model_name='acessos',
            name='webhook_ace_leitor__029c37_idx',
        ),
        migrations.RemoveIndex(
            model_name='acessos',
            name='webhook_ace_post_id_19f194_idx',
        ),
        migrations.RemoveIndex(
            model_name='acessos',
            name='webhook_ace_post_id_71f1ca_idx',
        ),
        migrations.AlterUniqueTogether(
            name='acessos',
            unique_together={('leitor', 'post', 'abertura_dia', 'abertura_hora')},
        ),
    ]
